apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: amq-mirroring-demo
#  annotations:
#    note: generated

secretGenerator:

# Remote cluster trust-store
- name: remote-cluster-truststore
  files:
  - broker.ks=./truststore.ts
  - client.ts=./truststore.ts
  literals:
  - keyStorePassword=password
  - trustStorePassword=password
