apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dc0

bases:
- ../../base

components:
  - ../../components/dc0-secrets
  - ../../components/dc0-truststore-secret

commonLabels:
  datacenter: dc0

patchesStrategicMerge:
- amq.yaml





